// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-8lFPbNXXRRHUdUeo-f9acFFstDaUzk',
    appId: '1:93828882916:web:45d388035576f09763a7f1',
    messagingSenderId: '93828882916',
    projectId: 'shopping-app-8289e',
    authDomain: 'shopping-app-8289e.firebaseapp.com',
    storageBucket: 'shopping-app-8289e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdknncUMileNS4QZZ9kQUA0ru93Ny4mI',
    appId: '1:93828882916:android:178800df12c1e58d63a7f1',
    messagingSenderId: '93828882916',
    projectId: 'shopping-app-8289e',
    storageBucket: 'shopping-app-8289e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAypp5bVLvUbKCjnZoE_9w8Vd7PW-jk1po',
    appId: '1:93828882916:ios:fe823ee25c0e823b63a7f1',
    messagingSenderId: '93828882916',
    projectId: 'shopping-app-8289e',
    storageBucket: 'shopping-app-8289e.appspot.com',
    iosBundleId: 'com.example.emailapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAypp5bVLvUbKCjnZoE_9w8Vd7PW-jk1po',
    appId: '1:93828882916:ios:fe823ee25c0e823b63a7f1',
    messagingSenderId: '93828882916',
    projectId: 'shopping-app-8289e',
    storageBucket: 'shopping-app-8289e.appspot.com',
    iosBundleId: 'com.example.emailapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh-8lFPbNXXRRHUdUeo-f9acFFstDaUzk',
    appId: '1:93828882916:web:d8e0765114ad7b2563a7f1',
    messagingSenderId: '93828882916',
    projectId: 'shopping-app-8289e',
    authDomain: 'shopping-app-8289e.firebaseapp.com',
    storageBucket: 'shopping-app-8289e.appspot.com',
  );
}
